class UserAccountPage
    PROFILE_USERNAME ||= "android.widget.TextView id:'account_profile_username'"
    PROFILE_SINCE ||= "android.widget.TextView id:'account_profile_member_since'"
    PROFILE_LOCATION ||= "android.widget.TextView id:'account_profile_location'"
    ACCOUNT_CREDIT ||= "android.widget.FrameLayout id:'account_credit_cell'"
    FEEDBACK ||= "android.widget.FrameLayout id:'feedback_cell'"
    MANAGE_NOTIFICATIONS ||= "android.widget.FrameLayout id:'manage_notifications_cell'"
    ADS_OPTIONS ||= "android.widget.FrameLayout id:'ad_options_cell'"
    CONTACT_US ||= "android.widget.FrameLayout id:'give_feedback_cell'"
    LOG_OUT ||= "android.widget.LinearLayout android.widget.TextView * marked:'Log out'"
    POPUP ||= "android.widget.FrameLayout id:'content'"
    LOGOUT_POPUP_CANCEL ||= "android.widget.LinearLayout android.widget.Button * marked:'Cancel'"
    LOGOUT_POPUP_CONFIRM ||= "android.widget.LinearLayout android.widget.Button * marked:'Confirm'"
    ACCOUNT_CREDIT_POPUP_OK ||= "android.widget.LinearLayout android.widget.Button * marked:'OK'"
end
